services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=wyett
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data: 